// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// wrap_around_c2
int wrap_around_c2(int x, IntegerVector y);
RcppExport SEXP _adventofcode18_wrap_around_c2(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(wrap_around_c2(x, y));
    return rcpp_result_gen;
END_RCPP
}
// run_marbles_c_scores
IntegerVector run_marbles_c_scores(int x, int marbles);
RcppExport SEXP _adventofcode18_run_marbles_c_scores(SEXP xSEXP, SEXP marblesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type marbles(marblesSEXP);
    rcpp_result_gen = Rcpp::wrap(run_marbles_c_scores(x, marbles));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adventofcode18_wrap_around_c2", (DL_FUNC) &_adventofcode18_wrap_around_c2, 2},
    {"_adventofcode18_run_marbles_c_scores", (DL_FUNC) &_adventofcode18_run_marbles_c_scores, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_adventofcode18(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
