# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
wrap_around_c2 <- function(x, y) {
    .Call(`_adventofcode18_wrap_around_c2`, x, y)
}

#' @export
run_marbles_c_scores <- function(x, marbles) {
    .Call(`_adventofcode18_run_marbles_c_scores`, x, marbles)
}

